import type { Metadata } from "next";
import localFonts from "next/font/local";
import "./globals.css";

const generalSans = localFonts({src: '../fonts/GeneralSans-Variable.woff2'})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${generalSans.className} bg-background`}>{children}</body>
    </html>
  );
}
